const NOT_FOUND_CODE = 404;

const DEFAULT_ERROR_CODE = 500;

const NOT_FOUND_MESSAGE = 'Данные не найдены';

const DEFAULT_ERROR_MESSAGE = 'Произошла ошибка';

const FIRST_PAGE_ELEMENTS_COUNT = 20;

const NEXT_PAGE_ELEMENTS_COUNT = 10;

module.exports = {
    NOT_FOUND_CODE,
    DEFAULT_ERROR_CODE,
    NOT_FOUND_MESSAGE,
    DEFAULT_ERROR_MESSAGE,
    NEXT_PAGE_ELEMENTS_COUNT,
    FIRST_PAGE_ELEMENTS_COUNT,
};
